# PyTorch Nightly PyTorch Tests Builds Pipeline on Azure DevOps
#
# This pipeline runs custom PyTorch unit-tests on nightly
# PyTorch wheels.

stages:
- stage: 'NightlyCustomTests'
  displayName: 'Run custom unit tests on PyTorch wheels'
  jobs:
  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_CPU_docker
      pool: $(BUILD_POOL_LIN_1)
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Nightly_Custom_Tests:
          container_image: $(CONTAINER_IMAGE_LIN_1)
          PYTHON_VERSION: $(PYTHON_VERSION_LIN_1)
          CUDA_VERSION: $(CUDA_VERSION_LIN_1)
          RUN_TESTS: $(RUN_TESTS_LIN)

  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_GPU_docker
      pool: $(BUILD_POOL_LIN_2)
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Nightly_Custom_Tests:
          container_image: $(CONTAINER_IMAGE_LIN_2)
          PYTHON_VERSION: $(PYTHON_VERSION_LIN_2)
          CUDA_VERSION: $(CUDA_VERSION_LIN_2)
          RUN_TESTS: $(RUN_TESTS_LIN)

  - template: job_templates/pytorch-template-win.yml
    parameters:
      name: windows_2019_CPU
      pool: $(BUILD_POOL_WIN_1)
      customMatrixes:
        Nightly_Custom_Tests:
          PYTHON_VERSION: $(PYTHON_VERSION_WIN_1)
          CUDA_VERSION: $(CUDA_VERSION_WIN_1)
          RUN_TESTS: $(RUN_TESTS_WIN)

  - template: job_templates/pytorch-template-win.yml
    parameters:
      name: windows_2019_GPU
      pool: $(BUILD_POOL_WIN_2)
      customMatrixes:
        Nightly_Custom_Tests:
          PYTHON_VERSION: $(PYTHON_VERSION_WIN_2)
          CUDA_VERSION: $(CUDA_VERSION_WIN_2)
          RUN_TESTS: $(RUN_TESTS_WIN)
