# PyTorch Nightly PyTorch Tests Builds Pipeline on Azure DevOps
#
# This pipeline runs custom PyTorch unit-tests on nightly
# PyTorch wheels.

stages:
- stage: 'NightlyCustomTests'
  displayName: 'Run custom unit tests on PyTorch wheels'
  jobs:
  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_CPU_docker
      pool: 'PyTorch-Linux-CPU'
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Py_38:
          container_image: pytorchms.azurecr.io/ubuntu_1804_cpu_dev
          PYTHON_VERSION: 3.8
          CUDA_VERSION: cpu

  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_GPU_docker
      pool: 'PyTorch-Linux-GPU'
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Py_37_CUDA_102_cuDNN_7:
          container_image: pytorchms.azurecr.io/ubuntu_1804_cuda_102_cudnn_7_dev
          PYTHON_VERSION: 3.7
          CUDA_VERSION: 102

  - template: job_templates/pytorch-template-win.yml
    parameters:
      name: windows_2019_CPU
      pool: 'PyTorch-Win-CPU'
      customMatrixes:
        Py_37:
          PYTHON_VERSION: 3.7
          CUDA_VERSION: cpu

  - template: job_templates/pytorch-template-win.yml
    parameters:
      name: windows_2019_GPU
      pool: 'PyTorch-Win-GPU'
      customMatrixes:
        Py_38_CUDA_102_cuDNN_7:
          PYTHON_VERSION: 3.8
          CUDA_VERSION: 102
