# PyTorch PR PyTorch Tests Builds Pipeline on Azure DevOps
#
# This pipeline runs custom PyTorch unit-tests on PyTorch 
# wheels generated during PR builds.

stages:
- stage: 'EnsureArtifactsReady'
  displayName: 'Ensure PyTorch PR Linux GPU Artifacts are ready'
  jobs:
  - template: job_templates/check-artifact-status-template.yml
    parameters:
      name: Verify
      pool: 'PyTorch-Lin-CPU-Burstable-VMSS'
      customMatrixes:
        Ubuntu:
          TARGET_CIRCLECI_BUILD: $(TARGET_CIRCLECI_PR_BUILD_1)

- stage: 'PRCustomTests'
  displayName: 'Run custom unit tests on PyTorch wheels'
  dependsOn: EnsureArtifactsReady
  condition: succeeded()
  jobs:
  - template: job_templates/pytorch-template-unix.yml
    parameters:
      name: ubuntu_1804_GPU_docker
      pool: 'PyTorch-Linux-GPU'
      container_endpoint: pytorchms.azurecr.io
      customMatrixes:
        Py_36_CUDA_102_cuDNN_7:
          container_image: pytorchms.azurecr.io/ubuntu_1804_cuda_102_cudnn_7_dev
          PYTHON_VERSION: 3.6
          CUDA_VERSION: 102
          TARGET_CIRCLECI_BUILD: $(TARGET_CIRCLECI_PR_BUILD_1)
          RUN_TESTS: $(RUN_TESTS_LIN)
 