# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: EchoText
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo This run is to demonstrate possible GitHub Actions/Azure Pipelines integration through GitHub Repository Dispatch Events.
  displayName: Checkout mstfbl/pytorch & echo Explanatory Text
  
- job: GitHubActionsLint
  dependsOn: EchoText
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'GitHub Actions'
      method: 'POST'
      headers: |
        {
          "Content-Type":"application/json"
        }
      body: |
        {
          "event_type":"dispatch_event_lint"
        }
      urlSuffix: 'repos/mstfbl/pytorch/dispatches'
      waitForCompletion: 'false'
  displayName: Lint GitHub Action

- job: GitHubActionsDemonstrateClientPayload
  dependsOn: GitHubActionsLint
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'GitHub Actions'
      method: 'POST'
      headers: |
        {
          "Content-Type":"application/json"
        }
      body: |
        {
          "event_type":"dispatch_event_client_payload_demonstration",
          "client_payload": {"msg1":"Hello!", "msg2":"Demonstration complete."}
        }
      urlSuffix: 'repos/mstfbl/pytorch/dispatches'
      waitForCompletion: 'false'
  displayName: Client Payload Demonstration GitHub Action

- job: GitHubActionsCodeQL
  dependsOn: GitHubActionsDemonstrateClientPayload
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'GitHub Actions'
      method: 'POST'
      headers: |
        {
          "Content-Type":"application/json"
        }
      body: |
        {
          "event_type":"dispatch_event_codeql"
        }
      urlSuffix: 'repos/mstfbl/pytorch/dispatches'
      waitForCompletion: 'false'
  displayName: CodeQL GitHub Action