# PyTorch check artifacts status template

parameters:
  name: ''
  pool: ''
  customMatrixes: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 600
  strategy:
    matrix:
      ${{ insert }}: ${{parameters.customMatrixes}}
  pool:
    name: ${{ parameters.pool}}

  steps:
  - checkout: none

  - bash: printenv
    displayName: Print all envs visible

  # Delete pytorch_tests repo from previous builds if exists
  - bash: rm -rf pytorch_tests/
    displayName: Delete pytorch_tests repo from previous builds if exists

  # Clone PyTorch Tests repository
  - bash: |
      B64_PAT=$(printf "%s"":$ADOTOKEN" | base64)
      git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone $(AZURE_DEVOPS_PYTORCH_TESTS_REPO_URL)
      cd pytorch_tests
      git checkout mubal/add_linux_gpu_vmss
    env:
      ADOTOKEN: $(AZURE_DEVOPS_CLI_PAT)
    displayName: Clone PyTorch Tests repo
  
  - bash: python3 $(Build.SourcesDirectory)/pytorch_tests/scripts/download_circleci_wheel.py check
    displayName: Check PyTorch PR build status
